In [5]:
def vovelsandconsonants(String):
    vowels = "aeiouAEIOU"
    v = 0
    c = 0

    for char in String:
        if char.isalpha():
            if char in vowels:
                v += 1
            else:
                c += 1

    return v, c
String = input("Enter a string: ")
v, c = vovelsandconsonants(String)
print(f"Number of vowels: {v}")
print(f"Number of consonants: {c}")

Number of vowels: 2
Number of consonants: 3


In [9]:
import numpy as np
R1=int (input("Enter numbber of rows of mat A"))
C1=int (input("Enter number of columns of mat A"))
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))


A = np.array(entries).reshape(R1, C1)
print(A)
R2=int (input("Enter numbber of rows of mat B"))
C2=int (input("Enter number of columns of mat B"))
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
B = np.array(entries).reshape(R2, C2)
print(B)
print(A*B)

Enter the entries in a single line (separated by space): 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Enter the entries in a single line (separated by space): 
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [16]:
L1=[1,2,4,3948,203,12,23]
L2=[3,43,534,1,2,4,12]
x=0
for i in L1:
    if i in L2:
        x+=1
print(x)

4


In [ ]:

import numpy as np

R1 = int(input("Enter number of rows of matrix A: "))
C1 = int(input("Enter number of columns of matrix A: "))

print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))



A = np.array(entries).reshape(R1, C1)
print("Matrix A:")
print(A)

ATr = A.T
print("Transposed Matrix A:")
print(ATr)

Enter the entries in a single line (separated by space): 
Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed Matrix A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [34]:

import numpy as np
def square_matrix():
    num_r=int(input("Enter number of rows:"))
    num_c = int(input("Enter number of columns:"))
    if num_r==num_c:
        print("Enter the elements of the matrix:")
        A = np.array([[int(input()) for i in range(num_c)] for j in range(num_r)])
        print("Enter the argument:")
        m = int(input())
        print(pow(A,m))


square_matrix()

Enter the elements of the matrix:
Enter the argument:
[[   1   64]
 [ 729 4096]]


In [35]:
string1="chandrakiran"

def occurance(string):
    dict1={}
    for i in string:
        if i in dict1:
            dict1[i]+=1
        else:
            dict1[i]=1
        
    return (dict1)

a = occurance(string1)
print(max(a,key=a.get))

a
